version: 2.1

<<<<<<< HEAD
executors:
  docker-executor:
    docker:
      - image: circleci/node:14  # Use a Node.js image suitable for building React.js apps

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      
      # Check if Docker is installed and install if not
      - run:
          name: Check Docker installation
          command: |
            if ! command -v docker &> /dev/null
            then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
            else
              echo "Docker is already installed"
            fi
      
      # Install AWS CLI
=======
orbs:
  aws-cli: circleci/aws-cli@4.0

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
>>>>>>> origin/main
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
<<<<<<< HEAD
      
      # Install dependencies and build the React app
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build React app
          command: npm run build
      
      # Log in to AWS ECR
      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t my-react-app .
      
      # Tag Docker image
      - run:
          name: Tag Docker image
          command: |
            docker tag my-react-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-react-app:latest
      
      # Push Docker image to ECR
      - run:
          name: Push Docker image to ECR
          command: |
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-react-app:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push
=======
      - run:
          name: Log in to Amazon ECR for 
          command: |
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 480294271769.dkr.ecr.us-east-2.amazonaws.com
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t 480294271769.dkr.ecr.us-east-2.amazonaws.com/devopsfe:$TAG .
      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker push 480294271769.dkr.ecr.us-east-2.amazonaws.com/devopsfe:$TAG

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: agdev
>>>>>>> origin/main
