version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - aws-cli/setup:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: us-east-2
      - run:
          name: Log in to Amazon ECR
          command: |
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 180432984958.dkr.ecr.us-east-2.amazonaws.com
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t 180432984958.dkr.ecr.us-east-2.amazonaws.com/agdevops:$TAG .
      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker push 180432984958.dkr.ecr.us-east-2.amazonaws.com/agdevops:$TAG

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: agdev
