version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Log in to Amazon ECR
          command: |
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 480294271769.dkr.ecr.us-east-2.amazonaws.com
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t 480294271769.dkr.ecr.us-east-2.amazonaws.com/devopsfe:$TAG .
      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker push 480294271769.dkr.ecr.us-east-2.amazonaws.com/devopsfe:$TA

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context: agdev
